@hostname = http://localhost/public/api
@port = 80
@host = {{hostname}}:{{port}}
@contentType = application/json

@token = 

### Url para teste após a criação do projeto.
GET http://localhost/public

###
GET {{host}}

### Url para criação do registro de um novo usuário.
POST {{host}}/admin/register
content-type: {{contentType}}
accept: {{contentType}},text/*;q=0.99

{
    "name": "Admin",
    "email": "tecnicoroot@gmail.com",
    "password": "1qaz2wsx"
}

### Url para efetuar o login e senha
POST {{host}}/login
content-type: {{contentType}}
accept: {{contentType}},text/*;q=0.99

{
    "email": "tecnicoroot@gmail.com",
    "password": "1qaz2wsx"
}

### Url para efetuar o login.
POST {{host}}/login
content-type: {{contentType}}
accept: {{contentType}},text/*;q=0.99

{
    "grant_type" : "credential",
    "client_id": "client_id_2ddc0f5f-adc0-4a99-a8dc-8a69cd5578c5", 
    "client_secret" : "client_secret_c2c77594-ebbe-4e1d-941f-b6e81108b46b"
}
### Url para testar a área protegida. Com o envio do token
GET  {{host}}/admin/me
content-type: {{contentType}}
accept: {{contentType}},text/*;q=0.99
Authorization: Bearer {{token}}

### E-mail

GET  http://localhost/public/send
