@hostname = http://localhost/public/api/v1
@port = 80
@host = {{hostname}}
@contentType = application/json
@token = ""

### Url para efetuar o login e senha
POST {{host}}/login
content-type: {{contentType}}
accept: {{contentType}},text/*;q=0.99

{
    "email": "tecnicoroot@gmail.com",
    "password": "1qaz2wsx"
}

### Url para efetuar o login.
POST {{host}}/login
content-type: {{contentType}}
accept: {{contentType}},text/*;q=0.99

{
    "grant_type" : "credential",
    "client_id": "client_id_090ea978-706d-4f3b-8037-deca2e20599d",
    "client_secret": "client_secret_516d3e9b-3879-4f91-9a78-508b46394eba"
}
### Url para testar a área protegida. Com o envio do token
GET  {{host}}/admin/me
content-type: {{contentType}}
accept: {{contentType}},text/*;q=0.99
Authorization: Bearer {{token}}

### E-mail

GET http://localhost/public/send
###

GET http://localhost/